---
- hosts: dbserver
  become: true
  vars: 
    wp_mysql_db: wordpress
    wp_mysql_user: wordpress
    wp_mysql_password: randompassword

  tasks:
    - name: Install required software
      apt: name={{ item }} state=present
      become: yes
      with_items:
       - apache2
       - mysql-server
       - php7.2-mysql
       - php7.2
       - libapache2-mod-php7.2
       - python-mysqldb

    - name: Create mysql database
  
      mysql_db: name={{ wp_mysql_db }} state=present
      become: yes

    - name: Create mysql user
      mysql_user: 
        name={{ wp_mysql_user }} 
        password={{ wp_mysql_password }} 
        priv=*.*:ALL

      become: yes
